spring.application.name=webApplication
# don't listen to ChatGPT to use spring.data.mongodb
# the keyword 'data' is what is causing the app to not run
spring.mongodb.uri=mongodb://root:secret@mongodb:27017/quizdatabase?authSource=admin