spring.application.name=webApplication
spring.mongodb.uri=mongodb://root:secret@mongodb:27017/quizdatabase
spring.mongodb.database: quizdatabase
spring.data.mongodb.username: root
spring.data.mongodb.password: secret